export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const SIGN_UP_EMAIL_CONFIRMATION_SUCCESS = 'SIGN_UP_EMAIL_CONFIRMATION_SUCCESS'
export const SIGN_UP_EMAIL_CONFIRMATION_FAIL = 'SIGN_UP_EMAIL_CONFIRMATION_FAIL'

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const USER_LOADED_ERROR = 'USER_LOADED_ERROR'

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const GET_PEOPLE = 'GET_PEOPLE';
export const GET_PEOPLE_ERROR = 'GET_PEOPLE_ERROR';

export const UPDATE_CONTACTS_FOR_FOLLOWER = 'UPDATE_CONTACTS_FOR_FOLLOWER'
export const UPDATE_CONTACTS_FOR_FOLLOWER_ERROR = 'UPDATE_CONTACTS_FOR_FOLLOWER_ERROR'

export const UPDATE_CONTACTS_FOR_PEOPLE = 'UPDATE_CONTACTS_FOR_PEOPLE'
export const UPDATE_CONTACTS_FOR_PEOPLE_ERROR = 'UPDATE_CONTACTS_FOR_PEOPLE_ERROR'

export const UPDATE_CONTACTS_FOR_FOLLOWING = 'UPDATE_CONTACTS_FOR_FOLLOWING'
export const UPDATE_CONTACTS_FOR_FOLLOWING_ERROR = 'UPDATE_CONTACTS_FOR_FOLLOWING_ERROR'

export const GET_FOLLOWER = 'GET_FOLLOWER';
export const GET_FOLLOWER_ERROR = 'GET_FOLLOWER_ERROR';

export const GET_FOLLOWING = 'GET_FOLLOWING';
export const GET_FOLLOWING_ERROR = 'GET_FOLLOWING_ERROR';

export const GET_EDIT_PROFILE = 'GET_EDIT_PROFILE';
export const GET_EDIT_PROFILE_ERROR = 'GET_EDIT_PROFILE_ERROR';

export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';

export const GET_POSTS = 'GET_POSTS';
export const POSTS_ERROR = 'POSTS_ERROR';

export const UPDATE_LIKE = 'UPDATE_LIKE';
export const UPDATE_LIKE_ERROR = 'UPDATE_LIKE_ERROR';

export const UPDATE_BOOKMARK = 'UPDATE_BOOKMARK';
export const UPDATE_BOOKMARK_ERROR = 'UPDATE_BOOKMARK_ERROR';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const SUBMIT_POST_REPORT = 'SUBMIT_POST_REPORT';
export const SUBMIT_POST_REPORT_ERROR = 'SUBMIT_POST_REPORT_ERROR';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

export const GET_POST = 'GET_POST';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const UPDATE_LIKE_DETAIL_POST = 'UPDATE_LIKE_DETAIL_POST';
export const UPDATE_LIKE_DETAIL_POST_ERROR = 'UPDATE_LIKE_DETAIL_POST_ERROR';

export const UPDATE_BOOKMARK_DETAIL_POST = 'UPDATE_BOOKMARK_DETAIL_POST';
export const UPDATE_BOOKMARK_DETAIL_POST_ERROR = 'UPDATE_BOOKMARK_DETAIL_POST_ERROR';

export const GET_COMMENTS_DETAIL_POST = 'GET_COMMENTS_DETAIL_POST';
export const GET_COMMENTS_DETAIL_POST_ERROR = 'GET_COMMENTS_DETAIL_POST_ERROR';

export const DELETE_COMMENT_DETAIL_POST = 'DELETE_COMMENT_DETAIL_POST';
export const DELETE_COMMENT_DETAIL_POST_ERROR = 'DELETE_COMMENT_DETAIL_POST_ERROR';

export const CREATE_COMMENT_DETAIL_POST = 'CREATE_COMMENT_DETAIL_POST';
export const CREATE_COMMENT_DETAIL_POST_ERROR = 'CREATE_COMMENT_DETAIL_POST_ERROR';

export const CREATE_COMMENT_LIST_POST = 'CREATE_COMMENT_LIST_POST';
export const CREATE_COMMENT_LIST_POST_ERROR = 'CREATE_COMMENT_LIST_POST_ERROR';

export const GET_TIMELINE_POST = 'GET_TIMELINE_POST';
export const GET_TIMELINE_POST_ERROR = 'GET_TIMELINE_POST_ERROR';

export const GET_BOOKMARK_POST = 'GET_BOOKMARK_POST';
export const GET_BOOKMARK_POST_ERROR = 'GET_BOOKMARK_POST_ERROR';

export const UPDATE_LIKE_FOR_BOOKMARK_LIST = 'UPDATE_LIKE_FOR_BOOKMARK_LIST';
export const UPDATE_LIKE_FOR_BOOKMARK_LIST_ERROR = 'UPDATE_LIKE_FOR_BOOKMARK_LIST_ERROR';

export const UPDATE_BOOKMARK_FOR_BOOKMARK_LIST = 'UPDATE_BOOKMARK_FOR_BOOKMARK_LIST';
export const UPDATE_BOOKMARK_FOR_BOOKMARK_LIST_ERROR = 'UPDATE_BOOKMARK_FOR_BOOKMARK_LIST_ERROR';

export const CREATE_COMMENT_BOOKMARK_POST_LIST = 'CREATE_COMMENT_BOOKMARK_POST_LIST';
export const CREATE_COMMENT_BOOKMARK_POST_LIST_ERROR = 'CREATE_COMMENT_BOOKMARK_POST_LIST_ERROR'

export const DELETE_POST_FROM_BOOKMARK_POST_LIST = 'DELETE_POST_FROM_BOOKMARK_POST_LIST';
export const DELETE_POST_FROM_BOOKMARK_POST_LIST_ERROR = 'DELETE_POST_FROM_BOOKMARK_POST_LIST_ERROR';




// export const GET_POSTS = 'GET_POSTS';
// export const POSTS_ERROR = 'POSTS_ERROR';

// export const GET_POST = 'GET_POST';
// export const DELETE_POST = 'DELETE_POST';
// export const POST_ERROR = 'POST_ERROR';

// export const ADD_POST = 'ADD_POST';

// export const PROFILE_ERROR = 'PROFILE_ERROR';



// export const GET_MYPOSTS = 'GET_MYPOSTS';
// export const MYPOSTS_ERROR = 'MYPOSTS_ERROR';

// export const UPDATE_LIKES = 'UPDATE_LIKES'
// export const UPDATE_LIKES_ERROR = 'UPDATE_LIKES_ERROR'

// export const UPDATE_BOOKMARKS = 'UPDATE_BOOKMARKS'
// export const UPDATE_BOOKMARKS_ERROR = 'UPDATE_BOOKMARKS_ERROR'


// export const UPDATE_CONTACTS_FOLLOWER_PAGE = 'UPDATE_CONTACTS_FOLLOWER_PAGE'
// export const UPDATE_CONTACTS_FOLLOWER_PAGE_ERROR = 'UPDATE_CONTACTS_FOLLOWER_PAGE_ERROR'

// export const UPDATE_CONTACTS_FOLLOWING_PAGE = 'UPDATE_CONTACTS_FOLLOWING_PAGE'
// export const UPDATE_CONTACTS_FOLLOWING_PAGE_ERROR = 'UPDATE_CONTACTS_FOLLOWING_PAGE_ERROR'


// export const UPDATE_FOLLOWING_LIST = 'UPDATE_FOLLOWING_LIST'
// export const UPDATE_FOLLOWING_LIST_ERROR = 'UPDATE_FOLLOWING_LIST_ERROR'

// export const CREATE_POST = 'CREATE_POST'
// export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

// export const HANDLE_COMMENTBOX = 'HANDLE_COMMENTBOX'
// export const HANDLE_COMMENTBOX_ERROR = 'HANDLE_COMMENTBOX_ERROR'

// export const GET_COMMENTS = 'GET_COMMENTS'
// export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR'

// export const ADD_COMMENT = 'ADD_COMMENT'
// export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR'

// export const EDIT_PROFILE = 'EDIT_PROFILE'
// export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR'

// export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE'
// export const GET_CURRENT_PROFILE_ERROR = 'GET_CURRENT_PROFILE_ERROR'

// export const UPDATE_LIKES_FOR_S = 'UPDATE_LIKES_FOR_S'
// export const UPDATE_LIKES_FOR_S_ERROR = 'UPDATE_LIKES_FOR_S_ERROR'

// export const UPDATE_BOOKMARKS_FOR_S = 'UPDATE_BOOKMARKS_FOR_S'
// export const UPDATE_BOOKMARKS_FOR_S_ERROR = 'UPDATE_BOOKMARKS_FOR_S_ERROR'

// export const EDIT_POST = 'EDIT_POST'
// export const EDIT_POST_ERROR = 'EDIT_POST_ERROR'
































